name: page_route_transition
description: A transition library that helps implement the page transition animation.
version: 3.0.0
homepage: https://github.com/mincheol-shin/transition

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
